Add more tests

diff --git a/.github/workflows/test-action.yml b/.github/workflows/test-action.yml
--- a/.github/workflows/test-action.yml
+++ b/.github/workflows/test-action.yml
@@ -44,7 +44,7 @@ jobs:
         id: reject-inaccessible-github-url
         uses: ./
         with:
-          repoPath: check-repo-action-clone
+          repoPath: clone-for-inaccessible-repo-url
           globs: README.md
           submissionJsonPath: test/non-existent-repo.json
           testMode: "true"
@@ -52,5 +52,54 @@ jobs:
         run: |
           if [ "${{ steps.reject-inaccessible-github-url.outputs.result }}" != "failure" ]; then
             echo "Action did not fail for an inaccessible GitHub repo URL"
+            exit 1
+          fi
+      - name: Action should fail for a GitHub repo where a file is missing
+        id: reject-github-repo-with-missing-file
+        uses: ./
+        with:
+          repoPath: clone-for-file-missing
+          globs: |-
+            README.md
+            test/this-does-not-exist.json
+          submissionJsonPath: test/valid-repo.json
+          testMode: "true"
+      - name: Report result of previous test
+        run: |
+          if [ "${{ steps.reject-github-repo-with-missing-file.outputs.result }}" != "failure" ]; then
+          echo "Action did not fail for a GitHub repo with a missing file"
+            exit 1
+          fi
+      - name: Action should fail for a GitHub repo where a folder is missing
+        id: reject-github-repo-with-missing-folder
+        uses: ./
+        with:
+          repoPath: clone-for-folder-missing
+          globs: |-
+            README.md
+            non-existent-folder/*
+          submissionJsonPath: test/valid-repo.json
+          testMode: "true"
+      - name: Report result of previous test
+        run: |
+          if [ "${{ steps.reject-github-repo-with-missing-folder.outputs.result }}" != "failure" ]; then
+            echo "Action did not fail for a GitHub repo with a missing folder"
+            exit 1
+          fi
+      - name: Action should succeed for a GitHub repo where no files or folders from globs are missing
+        id: accept-github-repo-with-matching-globs
+        uses: ./
+        with:
+          repoPath: clone-for-happy-path
+          globs: |-
+            action.yml
+            README.md
+            test/*
+          submissionJsonPath: test/valid-repo.json
+          testMode: "true"
+      - name: Report result of previous test
+        run: |
+          if [ "${{ steps.accept-github-repo-with-matching-globs.outputs.result }}" != "success" ]; then
+            echo "Action did not succeed for a valid GitHub repo with matching files and folders"
             exit 1
           fi
